CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Encomendas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Descricao" text NOT NULL,
    "Cliente" text,
    "Status" text NOT NULL,
    "ValorOrcado" numeric NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "DataFinalizacao" timestamp with time zone,
    "Observacao" text,
    CONSTRAINT "PK_Encomendas" PRIMARY KEY ("Id")
);

CREATE TABLE "ListasTarefa" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Titulo" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ListasTarefa" PRIMARY KEY ("Id")
);

CREATE TABLE "Materiais" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Nome" text NOT NULL,
    "Categoria" text NOT NULL,
    "Tamanho" text,
    "Quantidade" integer NOT NULL,
    "Valor" numeric NOT NULL,
    "Status" text NOT NULL,
    "DataEntrada" timestamp with time zone NOT NULL,
    "DataSaida" timestamp with time zone,
    CONSTRAINT "PK_Materiais" PRIMARY KEY ("Id")
);

CREATE TABLE "MovimentacoesFinanceiro" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Descricao" text NOT NULL,
    "Valor" numeric NOT NULL,
    "Contexto" text NOT NULL,
    "MeioPagamento" text NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MovimentacoesFinanceiro" PRIMARY KEY ("Id")
);

CREATE TABLE "PecasProntas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Titulo" text NOT NULL,
    "Descricao" text,
    "Valor" numeric NOT NULL,
    "FotoUrl" text,
    "Tipo" text NOT NULL,
    "Vendida" boolean NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PecasProntas" PRIMARY KEY ("Id")
);

CREATE TABLE "Tarefas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ListaTarefaId" integer NOT NULL,
    "Descricao" text NOT NULL,
    "Concluido" boolean NOT NULL,
    "DataConclusao" timestamp with time zone,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tarefas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tarefas_ListasTarefa_ListaTarefaId" FOREIGN KEY ("ListaTarefaId") REFERENCES "ListasTarefa" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MovimentacoesEstoque" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "MaterialId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "Tipo" text NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "Observacao" text,
    CONSTRAINT "PK_MovimentacoesEstoque" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MovimentacoesEstoque_Materiais_MaterialId" FOREIGN KEY ("MaterialId") REFERENCES "Materiais" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PecaProntaMateriais" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "PecaProntaId" integer NOT NULL,
    "MaterialId" integer NOT NULL,
    "QuantidadeUsada" integer NOT NULL,
    CONSTRAINT "PK_PecaProntaMateriais" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PecaProntaMateriais_Materiais_MaterialId" FOREIGN KEY ("MaterialId") REFERENCES "Materiais" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PecaProntaMateriais_PecasProntas_PecaProntaId" FOREIGN KEY ("PecaProntaId") REFERENCES "PecasProntas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Vendas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "PecaProntaId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "ValorVenda" numeric NOT NULL,
    "Cliente" text,
    "Data" timestamp with time zone NOT NULL,
    "Observacao" text,
    CONSTRAINT "PK_Vendas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vendas_PecasProntas_PecaProntaId" FOREIGN KEY ("PecaProntaId") REFERENCES "PecasProntas" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MovimentacoesEstoque_MaterialId" ON "MovimentacoesEstoque" ("MaterialId");

CREATE INDEX "IX_PecaProntaMateriais_MaterialId" ON "PecaProntaMateriais" ("MaterialId");

CREATE INDEX "IX_PecaProntaMateriais_PecaProntaId" ON "PecaProntaMateriais" ("PecaProntaId");

CREATE INDEX "IX_Tarefas_ListaTarefaId" ON "Tarefas" ("ListaTarefaId");

CREATE INDEX "IX_Vendas_PecaProntaId" ON "Vendas" ("PecaProntaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209185148_InitialPostgres', '8.0.0');

COMMIT;

